networks:
  backend:

services:
  api:
    image: api:1.0.0
    build:
      args:
        - DOCKER_USER=${USER}
      context: .
      dockerfile: api.Dockerfile
      target: dev
    env_file:
      - ./env/api.env
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app/api

  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: pony_db
      POSTGRES_USER: pony
      POSTGRES_PASSWORD: password
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: