output   = "./internal/models"
wipe     = true
no-tests = true
add-enum-types = true
no-auto-timestamps = false

[psql]
  dbname = "pony_db"
  host   = "psql"
  port   = 5432
  user   = "pony"
  pass   = "password"
  sslmode = "disable"
  blacklist = ["goose_db_version", "migrations", "other"]
