---
- name: Add secrets to makefile playbook
  hosts: local
  become: True
  gather_facts: True
  vars_files:
    - ./vars/secrets.yml

  tasks:
    - name: Add SQL migration path
      ansible.builtin.lineinfile:
        line: "{{ SQLMIGRATIONDIR }}"
        regexp: ^SQLMIGRATIONDIR := "<Add SQL migration path here>"
        path: ../../../../Makefile

    - name: Add SQL connection string
      ansible.builtin.lineinfile:
        line: "{{ SQLCONNSTR }}"
        regexp: ^SQLCONNSTR := "<Add SQL connection string here>"
        path: ../../../../Makefile

    - name: Add testing db SQL connection string
      ansible.builtin.lineinfile:
        line: "{{ TESTSQLCONNSTR }}"
        regexp: ^TESTSQLCONNSTR := "<Add testing db SQL connection string here>"
        path: ../../../../Makefile
